import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { MouseEventHandler, useState } from "react";
import Button from "../components/Button";
import CustomLink from "../components/CustomLink";
import Main from "../components/Main";

export default function Home() {
  const router = useRouter();
  const [count, setCount] = useState(0);

  const addCount = () => {
    setCount(count + 1);
  };

  const subCount = () => {
    setCount(count > 0 ? count - 1 : count);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1 className="text-5xl font-bold mb-10">
          Welcome to{" "}
          <a href="https://nextjs.org" className="text-blue-600">
            Next.js!
          </a>
        </h1>
        <div className="flex">
          <CustomLink href="/about" className="mr-3">
            About Page
          </CustomLink>
          <CustomLink href="/posts">SSG Posts</CustomLink>
        </div>
        <div className="flex flex-col justify-center items-center my-10 border-2 rounded p-5 border-dashed border-spacing-2">
          <div className="flex mb-3 items-center">
            <CounterButton onClick={subCount}>-</CounterButton>
            <span className="mx-3">
              Counter: <span>{count}</span>
            </span>
            <CounterButton onClick={addCount}>+</CounterButton>
          </div>
          <CustomLink href={`/posts/${count}`}>Go to dynamic page</CustomLink>
        </div>

        <Button link="/random">Random image page</Button>
      </Main>

      <footer className="text-center border-t-2 py-5">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image
              className="h-[1em] invert inline"
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </>
  );
}

interface ButtonProps {
  onClick: MouseEventHandler;
  children: string;
  className?: string;
}

const CounterButton: React.FC<ButtonProps> = ({
  onClick,
  children,
  className,
}) => {
  return (
    <button
      className={`inline-block border-2 px-2 pb-[2px] border-blue-600 text-blue-300 transition-colors duration-300 ease-out hover:bg-blue-600 hover:text-white rounded ${className}`}
      onClick={onClick}
    >
      {children}
    </button>
  );
};
